name: Install Extract APK
run-name: Install Extract - ${{inputs.run_name}}

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,15 * * *'
    
  workflow_dispatch:
    inputs:
      apk_zip_url:
        description: 'url to download apks zipped'
        required: true
        type: string
        default: https://url/apks.zip
      run_name:
        required: false
        type: string
env:
  avd_port: 9999
  avd_name: localhost:9999
  default_apk_zip_url: https://github.com/clearbluejar/apk-install/releases/download/v0.0.1/example.apk.zip
  all_apk_dir: all_apks

jobs:
  generate-matrix:    
    runs-on: ubuntu-latest    
    outputs:
      apkpaths: ${{ steps.getpaths.outputs.apkpaths }}
    steps:      
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download and unzip APKs
        run: |
          mkdir ${{env.all_apk_dir}}          
          [ -n "${{github.event.inputs.apk_zip_url}}" ] && wget "${{github.event.inputs.apk_zip_url}}" -O ${{env.all_apk_dir}}.zip
          [ -z "${{github.event.inputs.apk_zip_url}}" ] && wget ${{env.default_apk_zip_url}} -O ${{env.all_apk_dir}}.zip
          unzip ${{env.all_apk_dir}}.zip -d ${{env.all_apk_dir}}

      - name: Setup paths
        id: getpaths
        run: |                              
          # Anchor to base.apk to avoid running 3 times for one set of splits
          echo "apkpaths=$(python -c 'import pathlib; print([str(list(pathlib.Path.glob(pathlib.Path("${{env.all_apk_dir}}"),"**/base.apk"))[0])])')" >> "$GITHUB_OUTPUT"          
        shell: bash

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.all_apk_dir}}
          path: ${{env.all_apk_dir}}
          retention-days: 15

  download-install-and-extract:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        apkpath: ${{fromJson(needs.generate-matrix.outputs.apkpaths)}}
        # NOTE: armeabi-v7a will fail on GitHub runners without an x86_64 split APK!
        arch: ['x86_64', 'armeabi-v7a']        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name : install adb
        run: sudo apt install adb aapt
      - name: Install reDroid dependencies
        run: |
          sudo apt install linux-modules-extra-`uname -r`
          sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
      - name: Run emulator
        run: |
          mkdir -p data
          docker run -itd --rm --privileged --pull always -v $(pwd)/data:/data -p ${{env.avd_port}}:5555 redroid/redroid:12.0.0-latest          

      - name: Download runner artifacts 
        uses: actions/download-artifact@v4
        with:
          name: ${{env.all_apk_dir}}
          path: ${{env.all_apk_dir}}

      - name: adb connect install
        run: |                    
          adb connect ${{env.avd_name}}
          adb wait-for-device
          # Install all split APKs together
          adb -s ${{env.avd_name}} install-multiple --abi ${{matrix.arch}} $(find ${{env.all_apk_dir}} -name "*.apk")
          
      - name: adb start main activity
        run: |                    
          sleep 10
          ./adb-run.sh "${{matrix.apkpath}}"
          # Wait for Superpack decompression to complete
          sleep 20

      - name: get package name ver
        id: info
        continue-on-error: true
        run : |
          VER=$(./get-pkgver.sh '${{matrix.apkpath}}' || echo "unknown")
          PKG=$(./get-pkg.sh '${{matrix.apkpath}}' || echo "com.whatsapp")
          echo "apkpkgver=$VER" >> "$GITHUB_ENV"
          echo "apkpkg=$PKG" >> "$GITHUB_ENV"

      - name: create output dir
        run: | 
          # Ensure a directory exists even if the previous steps failed
          mkdir -p "${{ env.apkpkgver }}"

      - name: aapt dump badging
        continue-on-error: true
        run: | 
          aapt dump badging "${{matrix.apkpath}}" > "${{ env.apkpkgver }}/badging.txt"
      
      - name: fix data permissions
        if: always()
        run: | 
          docker stop $(docker ps -a -q) || true
          sudo chown -R runner:runner data || true

      - name: compress archive data
        continue-on-error: true
        run: |
          mv data "data-${{ matrix.arch }}"
          tar cvzf "${{ env.apkpkgver }}/extracted_${{ matrix.arch }}.tar.gz" "data-${{ matrix.arch }}/data/${{ env.apkpkg }}" || true
      
      - name: Upload extracted data
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: package_data_${{ matrix.arch }}
            path: ${{ env.apkpkgver }}
            retention-days: 7
            
      - name: Upload full emulator data
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: full_data_${{ matrix.arch }}
            path: data-${{ matrix.arch }}/data/
            retention-days: 1
